import React from 'react'
import {gql,useQuery} from '@apollo/client';
import QRCode from 'qrcode.react'
import Head from 'next/head';
import Script from 'next/script'

const OBTENER_MESAS = gql`
    query Query {
        obtenerMesas {
            id
            nombre
        }
    }
`;

const imprimirqr = () => {
  const {data,loading,error} = useQuery(OBTENER_MESAS);
  if(loading){
    return(<p>Cargando...</p>)
  }

  const {obtenerMesas} = data;

  return(
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="/styles/style.css"/>
      
    </Head>
      <Script src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></Script>
      <div className="w-full">
        <div className="grid grid-cols-3 gap-4 ">
        {obtenerMesas.map(mesa => (
          <QRCode value={mesa.id} />
        ))}
      </div>
      </div>
    
    </>
  )
}

export default imprimirqr;