import React from 'react';
import Head from 'next/head';



const HeadApp = () => {
  return(
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="/styles/style.css"/>
      <script type="text/javascript" src="asdasdasdasda"></script>
    </Head>
  )
}
export default HeadApp;